version: '3.8'

services:
  backend:
    container_name: mini-focus-be
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
    command: /bin/sh -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: mini-focus-fe
    ports:
      - "3000:80"
    depends_on:
      - backend