"""add_parent_id_to_projects

Revision ID: 20ca453c9f27
Revises: 3621ed46c007
Create Date: 2025-06-18 18:37:26.217817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ca453c9f27'
down_revision: Union[str, None] = '3621ed46c007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects') as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_projects_parent_id', 'projects', ['parent_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects') as batch_op:
        batch_op.drop_constraint('fk_projects_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')
    # ### end Alembic commands ###
