"""add status and is_flagged to projects and action items

Revision ID: 3621ed46c007
Revises: b7f6d0e34a2b
Create Date: 2025-06-07 15:14:54.137628

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3621ed46c007"
down_revision: Union[str, None] = "b7f6d0e34a2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "action_items",
        sa.Column(
            "status", sa.String(), nullable=False, server_default="todo"
        ),
    )
    op.add_column(
        "action_items",
        sa.Column(
            "is_flagged", sa.Boolean(), nullable=False, server_default="0"
        ),
    )
    op.drop_column("action_items", "is_completed")
    op.add_column(
        "projects",
        sa.Column(
            "status", sa.String(), nullable=False, server_default="todo"
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "is_flagged", sa.Boolean(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "is_flagged")
    op.drop_column("projects", "status")
    op.add_column(
        "action_items",
        sa.Column(
            "is_completed", sa.BOOLEAN(), nullable=False, server_default="0"
        ),
    )
    op.drop_column("action_items", "is_flagged")
    op.drop_column("action_items", "status")
    # ### end Alembic commands ###
