"""remove unique constraint from project name

Revision ID: b7f6d0e34a2b
Revises: a6431aa3acd9
Create Date: 2025-06-07 14:37:40.424189

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7f6d0e34a2b"
down_revision: Union[str, None] = "a6431aa3acd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.create_index(
        op.f("ix_projects_name"), "projects", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=1)
    # ### end Alembic commands ###
